spring:
  application:
    name: restserver

server:
  port: 8443
  ssl:
    enabled: true
    #need to change wth your own domain's certificate
    key-store: classpath:cert.pfx
    key-store-type: PKCS12
    # need to set environment variable
    key-store-password: ${SSL_KEYSTORE_PASSWORD}